ALTER SESSION SET nls_date_format = 'DD-MM-YYYY';

-- Creo la tabla ROL
CREATE TABLE rol (
    id_tabla       NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1,
    field       VARCHAR(30) NOT NULL,
    CONSTRAINT pk_tabla PRIMARY KEY ( id_tabla ),
    CONSTRAINT uk_tabla_field UNIQUE ( field )
);

ALTER TABLE tabla
    ADD CONSTRAINT fk_tabla_tablaref FOREIGN KEY ( fk_field )
        REFERENCES tablaref ( id_tablaref );
