CREATE TABLE universidad (
    id_universidad  NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1,
    nombre          VARCHAR(30) NOT NULL,
    ubicacion       VARCHAR(50) NOT NULL,
    CONSTRAINT universidad_pk PRIMARY KEY ( id_universidad )
);

CREATE TABLE carrera (
    id_carrera      NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1,
    nombre          VARCHAR(30) NOT NULL,
    id_universidad  NUMBER NOT NULL,
    CONSTRAINT carrera_pk PRIMARY KEY ( id_carrera )
);

ALTER TABLE carrera
    ADD CONSTRAINT fk_carr_uni FOREIGN KEY ( id_universidad )
        REFERENCES universidad ( id_universidad );