CREATE TABLE CLIENTES (
NOMBRE VARCHAR(50),
APELLIDO VARCHAR(50),
CI VARCHAR(50),
CONSTRAINT PK_CLIENTE PRIMARY KEY (CI)
);


CREATE TABLE MASCOTAS (
NRO_PATENTE VARCHAR(50),
TIPO VARCHAR(50),
NOMBRE VARCHAR(50),
EDAD INTEGER,
CI_CLIENTE VARCHAR(50),
CONSTRAINT PK_MASCOTAS PRIMARY KEY (NRO_PATENTE)
);

ALTER TABLE MASCOTAS ADD CONSTRAINT FK_MASCOTA_CLIENTE FOREIGN KEY (CI_CLIENTE) REFERENCES CLIENTES(CI);

CREATE TABLE VETERINARIOS (
CODIGO VARCHAR(50),
ESPECIALIDAD VARCHAR(50),
NOMBRE VARCHAR(50),
CI VARCHAR(50),
CONSTRAINT PK_VETERINARIOS PRIMARY KEY (CODIGO)
);

CREATE TABLE CONSULTA (
NRO_PATENTE_MASCOTA VARCHAR(50),
CODIGO_VETERINARIO VARCHAR(50),
FECHA DATE,
CONSTRAINT PK_CONSULTA PRIMARY KEY (NRO_PATENTE_MASCOTA,FECHA)
);

ALTER TABLE CONSULTA ADD CONSTRAINT FK_CONSULTA_MASCOTA FOREIGN KEY (NRO_PATENTE_MASCOTA) REFERENCES MASCOTAS(NRO_PATENTE);
ALTER TABLE CONSULTA ADD CONSTRAINT FK_CONSULTA_VETERINARIO FOREIGN KEY (CODIGO_VETERINARIO) REFERENCES VETERINARIOS(CODIGO);

