package com.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2023-06-18T18:01:39.495-03:00
 * Generated source version: 3.4.5
 *
 */
@WebServiceClient(name = "tasaPatente",
                  wsdlLocation = "http://localhost:8080/RepasoJAXEje5/tasaPatente?wsdl",
                  targetNamespace = "http://webservices.com/")
public class TasaPatente_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservices.com/", "tasaPatente");
    public final static QName TasaPatentePort = new QName("http://webservices.com/", "TasaPatentePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/RepasoJAXEje5/tasaPatente?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TasaPatente_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/RepasoJAXEje5/tasaPatente?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TasaPatente_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TasaPatente_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TasaPatente_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public TasaPatente_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TasaPatente_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TasaPatente_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns TasaPatente
     */
    @WebEndpoint(name = "TasaPatentePort")
    public TasaPatente getTasaPatentePort() {
        return super.getPort(TasaPatentePort, TasaPatente.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TasaPatente
     */
    @WebEndpoint(name = "TasaPatentePort")
    public TasaPatente getTasaPatentePort(WebServiceFeature... features) {
        return super.getPort(TasaPatentePort, TasaPatente.class, features);
    }

}
