package com.cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2023-06-18T18:01:39.475-03:00
 * Generated source version: 3.4.5
 *
 */
@WebService(targetNamespace = "http://webservices.com/", name = "TasaPatente")
@XmlSeeAlso({ObjectFactory.class})
public interface TasaPatente {

    @WebMethod
    @RequestWrapper(localName = "estimar", targetNamespace = "http://webservices.com/", className = "com.cliente.Estimar")
    @ResponseWrapper(localName = "estimarResponse", targetNamespace = "http://webservices.com/", className = "com.cliente.EstimarResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String estimar(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0
    );
}
